# Howe often changing data is saved to config, in ticks (20 ticks = 1 second)
fileSaveTicks: 72000

cardSources:
  passive:
    - SKELETON_HORSE
    - ZOMBIE_HORSE
    - DONKEY
    - MULE
    - BAT
    - PIG
    - SHEEP
    - COW
    - CHICKEN
    - SQUID
    - WOLF
    - MUSHROOM_COW
    - SNOWMAN
    - OCELOT
    - IRON_GOLEM
    - HORSE
    - RABBIT
    - POLAR_BEAR
    - LLAMA
    - PARROT
    - VILLAGER
    - TURTLE
    - COD
    - SALMON
    - PUFFERFISH
    - TROPICAL_FISH
    - DOLPHIN
    - CAT
    - PANDA
    - TRADER_LLAMA
    - WANDERING_TRADER
    - FOX
    - BEE
    - STRIDER
    - AXOLOTL
    - GLOW_SQUID
    - GOAT
  hostile:
    - ELDER_GUARDIAN
    - WITHER_SKELETON
    - STRAY
    - HUSK
    - ZOMBIE_VILLAGER
    - EVOKER
    - VEX
    - VINDICATOR
    - ILLUSIONER
    - CREEPER
    - SKELETON
    - SPIDER
    - ZOMBIE
    - SLIME
    - GHAST
    - ZOMBIFIED_PIGLIN
    - ENDERMAN
    - CAVE_SPIDER
    - SILVERFISH
    - BLAZE
    - MAGMA_CUBE
    - WITCH
    - ENDERMITE
    - GUARDIAN
    - SHULKER
    - PHANTOM
    - DROWNED
    - PILLAGER
    - RAVAGER
    - HOGLIN
    - PIGLIN
    - ZOGLIN
    - PIGLIN_BRUTE
    - WARDEN
  boss:
    - ENDER_DRAGON

# Chances for cards
chances:
  # Chance of a card dropping
  # Format is a number between 0 and 1, where 0 is 0% chance and 1 is 100% chance
  shiny: 0.01
  drop:
    passive: 0.01
    hostile: 0.01
    boss: 1
  # Chance for each rarity
  # format is a weight system - each weight from each rarity is summed, and used to compute the chance
  # so for example, weights of 100 for common, 50 for uncommon, 10 for rare, 5 for very rare and 1 for legendary means that there is a 1/166 chance of legendary
  # A value of 0 prevents that card rarity dropping for that source
  rarity:
    common:
      passive: 100000
      hostile: 100000
    uncommon:
      passive: 20000
      hostile: 50000
    rare:
      hostile: 5000
    very_rare:
      hostile: 1000
      boss: 2
    legendary:
      hostile: 1
      boss: 1

  useSpecificChances: true
  specificChances:
    ELDER_GUARDIAN:
      dropRate: 1
      rarityWeights:
        rare: 60
        very_rare: 30
        legendary: 10
    WITHER:
      dropRate: 1
      rarityWeights: 1
        very_rare: 20
        legendary: 10
    ENDER_DRAGON:
      dropRate: 1
        rarityWeights: 1
          very_rare: 20
          legendary: 10

# This is where booster packs are defined.
# If a card rarity is not included, it is assumed the amount is 0
# All cards from a booster pack are randomly generated
boosterpacks:
  starter_pack:
    name: "Starter Pack"
    common: 9
    rare: 1
  advanced_pack:
    name: "Advanced Pack"
    common: 12
    uncommon: 6
    rare: 2
  expert_pack:
    name: "Expert Pack"
    uncommon: 6
    rare: 4
    very_rare: 2
  ultimate_pack:
    name: "Ultimate Pack"
    rare: 5
    legendary: 1